### ISSUE TITLE
Error second time use of startSequenceAcquisition

### ISSUE THREAD

**Issue by felix92** [micro-manager/pymmcore#22]
Hallo,
I use the MicroManager2.0 to control a Hamamatsu Camera with python.
When I use the function startSequenceAcquisition with NumberofImages = 1 the first time after initialization an image is recorded. When I use his function a second time an error is throwing.

`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Micro-Manager-2.0gamma\MMCorePy.py", line 5532, in startSequenceAcqui
sition
    return _MMCorePy.CMMCore_startSequenceAcquisition(self, *args)
MMCorePy.CMMError: Error in device "camera": Unknown error in the device (1)  
`

I hope somebody can help me.
Thanks,
Felix

**Comment by nicost** [comment]
Just out of curiosity: did you try calling stopSequenceAcquisition() before starting a Sequence the second time?

**Comment by felix92** [comment]
Yes, I tried it but I got the same error.

**Comment by nicost** [comment]
Do you get the same error, when you run this code from a Beanshell script (i.e., within the MM GUI)?

**Comment by marktsuchida** [comment]
I second @nicost's question; it is especially worth testing if this is caused by the fact that you are manually "loading" the camera device instead of using a config file via `mmc.loadSystemConfiguration()`. This is because a (correct) config file contains lines that "reset" the Core in addition to loading the devices.

And just to confirm, this is specific to Hamamatsu (i.e. doesn't happen if you run the same code with DemoCamera), correct?

**Comment by marktsuchida** [comment]
Closing inactive issues. Please reopen with results from latest versions if the problem persists.
