### ISSUE TITLE
Failure to load Raptor EPIX device

### ISSUE THREAD

**Issue by anntzer** [micro-manager/pymmcore#41]
Dear maintainers,
I am having trouble loading a Raptor EPIX camera (https://micro-manager.org/wiki/RaptorEPIX) using pymmcore (py3.8), even though it loads fine with the MicroManager 1.4 GUI interface or with MMCorePy (py2.7).
`C:\Program Files\Micro-Manager-1.4` has been added to the $PATH and is the current directory.  With MMCorePy, the following works:
```
>>> import MMCorePy
>>> mmc = MMCorePy.CMMCore()
>>> mmc.loadDevice("Raptor Ninox Camera 640", "RaptorEPIX", "Raptor Ninox Camera 640")
>>> mmc.initializeAllDevices()
>>> mmc.setCameraDevice("Raptor Ninox Camera 640")
>>> mmc.snapImage()
```
but with pymmcore, the same code (with the modified import) fails at the `initializeAllDevices` stage with an error from the PIXCI driver:

> PIXCI(R) 64 Bit Library 3.08.00 [15.08.31]
> PIXCI(R) Configuration Error or Fault
> Operating system not supported
> Check Configuration!
> See `Installation` and `In Case of Trouble` in the PIXCI(R) User's Manual.

> Current operating system not supported

Is there perhaps anything to do to make pymmcore load the drivers in a way "more similar" to how MMCorePy does it?
Thanks in advance.

**Comment by marktsuchida** [comment]
The way pymmcore loads devices is fundamentally the same as MMCorePy, but the fact that the Python module lives in a different location may make it necessary to take extra steps. Please see the section [Loading device adapters on Windows](https://github.com/micro-manager/pymmcore#loading-device-adapters-on-windows) in the README file. Setting the current directory to the Micro-Manager folder is a good idea if you haven't tried that yet.

Also, it would be useful to make sure the camera works with the latest 2.0gamma GUI. From the information you provided, it could be that the difference is due to MMCorePy vs pymmcore, but it could also be due to the different Micro-Manager versions.

**Comment by anntzer** [comment]
Thank you for your quick reply.
I have read the linked document.  I did make sure that the current directory is `C:\Program Files\Micro-Manager-1.4` (both by starting Python from there and by os.chdir).
I have also been unable to make the camera work on the MM2.0 GUI (loading the MM1.4 config file or trying to create a new config using the Hardware Configuration Wizard both fail), but note that here I was trying to use pymmcore with MM1.4.

**Comment by marktsuchida** [comment]
In that case, there are two problems: (1) pymmcore only works with recent versions of 2.0gamma, so pointing it to the 1.4 installation will not work correctly (sorry if this was not clear), and more importantly (2) it looks like there is a problem with the EPIX device is with MM2.0 in general, and not specific to pymmcore.

Regarding (1): the pymmcore version needs to match the MMCore version; this is explained [here](https://github.com/micro-manager/pymmcore#matching-micro-manager-and-pymmcore-versions). But of course this will not fix your problem, because a device that doesn't work in the GUI will not work in pymmcore.

Regarding (2): would you mind creating an issue on the main Micro-Manager project https://github.com/micro-manager/micro-manager for this? It would be helpful if you could include the exact versions of 1.4 and 2.0 you tried (including date if nightly build), so that we can check what might have changed in the EPIX module.

**Comment by nicost** [comment]
Hi @anntzer, unlikely, but could it be that your 1.4 installation is 32 bit, and that - for whatever reason - your EPIX board needs 32 bits?  In any case, since the Raptor camera does not work for you in 2.0 (which as @marktsuchida explained, you need to use Pycro-Manager), I would contact Raptor support.

**Comment by anntzer** [comment]
Ah, sorry, I did not realize pymmcore required MM2.0 (AFAICT this is not mentioned in the README or the PyPI page, perhaps that should be noted explicitly there?)
Both of my MM (1.4 and 2.0) installs are 64 bit and use device API 69 and module API 10 (and the pymmcore API matches), so likely I'll need to contact Raptor/EPIX to fix the problem now (I assume MM got a closed source dll from them?); if that's the case feel free to close this issue.

**Comment by nicost** [comment]
The RaptorEpix adapter is build from source code that is (nearly) identical between 1.4 and 2.0.  Could you make a copy of the 1.4 mmgr_dal_RaptorEpix.dll and place it in your 2.0 directory and see if that works?  If it does, then there is a build issue.  If it does not, then I am confused.  Pinging @nanthony21 so that he is aware of potential build issues with this adapter in 2.0.

**Comment by anntzer** [comment]
Copying the mmgr_dal DLL from MM1.4 to MM2.0 doesn't help either.

**Comment by nicost** [comment]
What happened?  Same error?  In that case, are there any files that you are supposed to copy into the Micro-Manager directory?  With the same device adapter binaries, there are very few reasons for things not working (the only one I can think of is missing dependencies).

**Comment by anntzer** [comment]
Sorry for the slow reply (I ended up dusting my knowledge of Python 2 to interact with with MMCorePy).  Yes, the error is the same.  I didn't look more into whether more files needed to be copied -- there's many dlls in the MM1.4 directory, and it's not clear which one I would want to try copying...

**Comment by marktsuchida** [comment]
@anntzer Unfortunately there's nothing mentioned in our [device page for RaptorEPIX](https://micro-manager.org/wiki/RaptorEPIX), but I'm sure Raptor support (linked from that page -- they should be familiar with Micro-Manager) can tell you if you need to copy any DLLs (if so, they would likely be installed as part of the EPIX driver, which you probably needed to install when you first set up your camera).

Closing this issue, but please don't hesitate to open a new one at the micro-manager project if Raptor support can't resolve your problems with the MM2 GUI (or here, if you get the GUI working but still have problems with pymmcore).

**Comment by anntzer** [comment]
Thanks again for the prompt support.
